kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DATA = "/data"
  IPFS_PATH = "/data/ipfs"
  IPFS_PROFILE = "server"
  IPFS_LOGGING=""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data/ipfs"
  source = "ipfs_data"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  
[[services]]
  internal_port = 4001
  protocol = "tcp"

  [[services.ports]]
    port = 4001

  [services.concurrency]
    type = "connections"
    hard_limit = 1000

[[services]]
  internal_port = 4001
  protocol = "udp"

  [[services.ports]]
    port = 4001
  [services.concurrency]
    type = "connections"
    hard_limit = 1000